;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Air.Combo1",DevComment="")
+GameplayTagList=(Tag="Ability.Air.Combo2",DevComment="")
+GameplayTagList=(Tag="Ability.Air.Combo3",DevComment="")
+GameplayTagList=(Tag="Ability.Air.Combo4",DevComment="")
+GameplayTagList=(Tag="Ability.Melee.Combo1",DevComment="Attack 1 of Melee Combo")
+GameplayTagList=(Tag="Ability.Melee.Combo2",DevComment="Attack 2 of Melee Combo")
+GameplayTagList=(Tag="Ability.Melee.Combo3",DevComment="Attack 3 of Melee Combo. Critical hit with 2x Damage")
+GameplayTagList=(Tag="Ability.OmniSlash.Activate",DevComment="")
+GameplayTagList=(Tag="Ability.Ranged.Aim",DevComment="Aiming in Ranged Stance")
+GameplayTagList=(Tag="Ability.Ranged.Fire",DevComment="Firing in Ranged Stance")
+GameplayTagList=(Tag="Ability.Ranged.Reload",DevComment="Reloading weapon in Ranged Stance")
+GameplayTagList=(Tag="Ability.Special",DevComment="Special Abiliy ")
+GameplayTagList=(Tag="Damage.Critical",DevComment="Critical Damage for Combo 3 of Melee Stance")
+GameplayTagList=(Tag="Data.Damage",DevComment="Damage data")
+GameplayTagList=(Tag="Event.Air.SlamTrigger",DevComment="")
+GameplayTagList=(Tag="Event.Melee.HitWindow",DevComment="")
+GameplayTagList=(Tag="Event.OmniSlash.Hit",DevComment="")
+GameplayTagList=(Tag="Stance.Melee",DevComment="Melee Stance")
+GameplayTagList=(Tag="Stance.Ranged",DevComment="Ranged Stance")
+GameplayTagList=(Tag="State.Aiming",DevComment="Is Aiming")
+GameplayTagList=(Tag="State.Airborne",DevComment="")
+GameplayTagList=(Tag="State.Cooldown.OmniSlash",DevComment="")
+GameplayTagList=(Tag="State.Cooldown.Special",DevComment="Special Ability in Cooldown")

